# Generated by Django 4.0.5 on 2022-06-22 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.stack'),
        ),
    ]
